---

dist: bionic

language: python
python:
  - 3.8
services: docker

env:
  global:
    - COLLECTION_NAME: arduino
  matrix:
    - MOLECULE_DISTRO_BOX: generic/ubuntu1804

install:
  - sudo add-apt-repository universe && sudo apt update
  - pip install molecule docker molecule-docker

before_script:
  - cd ../
  - mv ansible*$COLLECTION_NAME $COLLECTION_NAME
  - cd $COLLECTION_NAME/roles/arduino_setup

script:
- molecule test
