### REQUIRED

namespace: community

name: arduino

version: 1.0.0

readme: README.md

authors:
- Walid Shouman <eng.walidshouman@gmail.com>


### OPTIONAL but strongly recommended

description: A collection to install and wrap arduino-cli

license:
- MIT

license_file: 'LICENSE'

tags:
  - arduino
  - arduino-cli

dependencies: {}

repository: https://github.com/weshouman/ansible-collection-arduino

documentation: https://github.com/weshouman/ansible-collection-arduino

homepage: https://github.com/weshouman/ansible-collection-arduino

issues: https://github.com/weshouman/ansible-collection-arduino/issues
